<?php

use \Drupal\node\NodeInterface;
use \Drupal\views\ViewExecutable;

/**
 * Implements hook_views_pre_render
 *
 * @param \Drupal\views\ViewExecutable $view
 * @return void
 */
function carocim_vues_views_pre_render(ViewExecutable $view) {

    // Exclure l'actualité courante de la vue "A lire aussi"
    /*if ($view->id() == 'a_lire_aussi' && $view->current_display == 'block_1') {

        $node = \Drupal::routeMatch()->getParameter('node');
        if ($node instanceof NodeInterface) {
            $nid = $node->id();

            foreach ($view->result as $key => $value) {

                if ($value->nid == $nid) {
                    unset ($view->result[$key]);
                    break;
                }
            }
        }
    }*/
}